#!/bin/bash
cd "$( dirname "${BASH_SOURCE[0]}")"
export BLUE='\033[1;94m'
export RED='\033[1;91m'

title="$RED 		Hi BRO!) it's vpntvpn \n"
prompt=
options=("Install dependency" "Configure all" "Configure only Wi-Fi" "Configure only VPN" "Swap VPN1 and VPN2" "VPN1->Wi-Fi" "Namespace->VPN2->Wi-Fi" "VPN1->namespace->VPN2->Wi-Fi" "TOR->namespace->VPN2->Wi-Fi" "VPN1->TOR->namespace->VPN2->Wi-Fi" "VPN1" "Namespace->VPN2" "VPN1->namespace->VPN2" "TOR->namespace->VPN2" "VPN1->TOR->namespace->VPN2")

clear
echo -e -n  "$title"
PS3="$prompt "
select opt in "${options[@]}" "Quit"; do 

    case "$REPLY" in

    1 ) clear
		echo -e -n "$BLUE Installing dependency \n"
		src/dependency_installer 
		clear
		echo -e -n  "$RED Press ENTER to continue \n";continue;;
    2 ) clear
		echo -e -n "$BLUE Configure all \n"
		src/configure_all 
		clear
		echo -e -n  "$RED Press ENTER to continue \n";continue;;
    3 ) clear
		echo -e -n "$BLUE Configure only Wi-Fi \n"
		src/configure_wifi 
		clear
		echo -e -n  "$RED Press ENTER to continue \n";continue;;
    4 ) clear
		echo -e -n "$BLUE Configure only VPN \n"
		src/configure_vpn
		clear
		echo -e -n  "$RED Press ENTER to continue \n";continue;;
    5 ) clear
		echo -e -n "$BLUE Swap VPN1 and VPN2 \n"
		src/swap_vpn
		clear
		src/vpntvpn_swap
		clear
		src/swap_vpn
		clear
		echo -e -n  "$RED Press ENTER to continue \n";continue;;
	6 ) clear
		echo -e -n "$BLUE VPN1->Wi-Fi \n"
		src/startvpn
		clear
		src/stopvpn
		clear
		echo -e -n  "$RED Press ENTER to continue \n";continue;;
    7 ) clear
		echo -e -n "$BLUE Namespace->VPN2->Wi-Fi \n"
		src/vpnON
		clear
		src/vpnOFF
		clear
		echo -e -n  "$RED Press ENTER to continue \n";continue;;
    8 ) clear
		echo -e -n "$BLUE VPN1->namespace->VPN2->Wi-Fi \n"
		src/vpnvpnON
		clear
		src/vpnvpnOFF
		clear
		echo -e -n  "$RED Press ENTER to continue \n";continue;;
    9 ) clear
		echo -e -n "$BLUE TOR->namespace->VPN2->Wi-Fi \n"
		src/tvpnON
		clear
		src/tvpnOFF
		clear
		echo -e -n  "$RED Press ENTER to continue \n";continue;;
	10 ) clear
		echo -e -n "$BLUE VPN1->TOR->namespace->VPN2->Wi-Fi \n"
		src/vpntvpnON
		clear
		src/vpntvpnOFF
		clear
		echo -e -n  "$RED Press ENTER to continue \n";continue;;
	11 ) clear
		echo -e -n "$BLUE VPN1 \n"
		src/startvpnsys
		clear
		echo -e -n  "$RED Press ENTER to continue \n";continue;;
	12 ) clear
		echo -e -n "$BLUE Namespace->VPN2 \n"
		src/vpnnameON
		clear
		src/vpnnameOFF
		clear
		echo -e -n  "$RED Press ENTER to continue \n";continue;;
	13 ) clear
		echo -e -n "$BLUE VPN1->namespace->VPN2 \n"
		src/vpnvpnnameON
		clear
		src/vpnvpnnameOFF
		clear
		echo -e -n  "$RED Press ENTER to continue \n";continue;;
	14 ) clear
		echo -e -n "$BLUE TOR->namespace->VPN2 \n"
		src/tvpnnameON
		clear
		src/tvpnnameOFF
		clear
		echo -e -n  "$RED Press ENTER to continue \n";continue;;
	15 ) clear
		echo -e -n "$BLUE VPN1->TOR->namespace->VPN2 \n"
		src/vpntvpnnameON 
		clear
		src/vpntvpnnameOFF
		clear
		echo -e -n  "$RED Press ENTER to continue \n";continue;;

    $(( ${#options[@]}+1 )) ) clear; break;;
    *) echo -e -n  "$RED Invalid option. Try another one. \n";continue;;

    esac

done
