#!/bin/bash
cd "$( dirname "${BASH_SOURCE[0]}")"

read -p "Enter path to VPN1 config (~/vpn1config.ovpn) > " vpn1_conf
cp -r -f $vpn1_conf vpn1.ovpn

read -p "VPN1 with login pass? (y/n) > " vpn1_logpass

if [[ ! $vpn1_logpass =~ ^[Nn]$ ]]; 
then read -p "Enter VPN1 login (user) > " vpn1_login
	echo $vpn1_login | cat > vpn1.conf
	read -p "Enter VPN1 password (pass) > " vpn1_pass
	echo $vpn1_pass | cat >> vpn1.conf

elif [[ ! $vpn1_logpass =~ ^[Yy]$ ]]; 
then if [ -f vpn1.conf ]; 
		then sudo rm -r vpn1.conf
	fi

fi
