#!/bin/bash
export BLUE='\033[1;94m'
export RED='\033[1;91m'
cd "$( dirname "${BASH_SOURCE[0]}")"
sudo apt update
sudo apt install bash util-linux procps hostapd iproute2 iw haveged dnsmasq iptables xfce4-terminal net-tools openvpn tor nyx -y
clear
echo -e -n "$BLUE"
read -p "Create symblink for vpntvpn to /bin (y/n) > " symblink

if [[ ! $symblink =~ ^[Nn]$ ]]; 
then dir_script=$(pwd | rev | cut -c 5- | rev)
	echo '#!/bin/bash' | cat > /tmp/dir_script
	echo "cd $dir_script" | cat >> /tmp/dir_script
	echo './vpntvpn' | cat >> /tmp/dir_script
	sudo mv -f /tmp/dir_script /bin/vpntvpn
	sudo chmod +x /bin/vpntvpn
	clear
	echo -e -n "$RED After close this just write vpntvpn in xfce4-terminal"
	sleep 5

elif [[ ! $symblink =~ ^[Yy]$ ]];
then echo -e -n "$BLUE All Done"
	
fi
