#!/bin/bash
sleep 10
set -x

dist=$(cat /tmp/dist)

# Enable IP-forwarding.
sudo sysctl -w net.ipv4.ip_forward=1

ls /dev/pts/ | cat > /tmp/ttyold && xfce4-terminal --geometry=62x24 --hide-scrollbar --hide-toolbar && xfce4-terminal --geometry=62x24 --hide-scrollbar --hide-toolbar && ls /dev/pts/ | cat > /tmp/ttynew && grep -vf /tmp/ttyold /tmp/ttynew | sort -u > /tmp/tty
namespace=$(sed '1!d' /tmp/tty)
tor_nyx=$(sed '2!d' /tmp/tty)
sudo ./ttyecho -n /dev/pts/$tor_nyx "sudo nyx"
sudo ./ttyecho -n /dev/pts/$namespace "sudo ip netns exec protected sudo -u $USER -i"
