#!/bin/bash
sleep 8
set -x

dist=$(cat /tmp/dist)

# Enable IP-forwarding.
sudo sysctl -w net.ipv4.ip_forward=1

ls /dev/pts/ | cat > /tmp/ttyold && xfce4-terminal --geometry=62x24 --hide-scrollbar --hide-toolbar && ls /dev/pts/ | cat > /tmp/ttynew && grep -vf /tmp/ttyold /tmp/ttynew | sort -u > /tmp/tty
hotspot=$(sed '1!d' /tmp/tty)
sudo ./ttyecho -n /dev/pts/$hotspot $dist/HotSpotON
