#!/bin/bash
cd "$( dirname "${BASH_SOURCE[0]}")"
set -x

dist=$(cat /tmp/dist)

sudo mv /etc/NetworkManager/NetworkManager.old /etc/NetworkManager/NetworkManager.conf
nm_pid=$(sudo pidof NetworkManager)
sudo kill -HUP $nm_pid

xfce4-terminal --geometry=62x24 --hide-scrollbar --hide-toolbar --hide-borders --working-directory=$dist -e "./nameOFF_Wi-Fi"
sudo service tor stop
