#!/bin/bash
cd "$( dirname "${BASH_SOURCE[0]}")"
set -x

wifi_iface=$(sed '4!d' variables.conf)
local_ip=$(sed '2!d' variables.conf)
tor_port=$(sed '3!d' variables.conf)

tor_server="$local_ip $tor_port"
pwd | cat > /tmp/dist
dist=$(cat /tmp/dist)

cat /sys/class/net/$wifi_iface/phy80211/name > /tmp/wifi_phy
sudo cp /etc/NetworkManager/NetworkManager.conf /etc/NetworkManager/NetworkManager.old
sudo sed -i 15c\unmanaged-devices=interface-name:$wifi_iface NetworkManager.conf
sudo cp NetworkManager.conf /etc/NetworkManager/NetworkManager.conf
nm_pid=$(sudo pidof NetworkManager)
sudo kill -HUP $nm_pid
sudo service tor start
sleep 7
xfce4-terminal --geometry=62x24 --hide-scrollbar --hide-toolbar --hide-borders --working-directory=$dist -e "./nameON_Wi-Fi"

if [ -f vpn2.conf ]; 
	then 
		sudo ./namespaced-openvpn --socks-proxy $tor_server  --config vpn2.ovpn --auth-user-pass vpn2.conf
	else
		sudo ./namespaced-openvpn --socks-proxy $tor_server  --config vpn2.ovpn
fi
