#!/bin/bash
cd "$( dirname "${BASH_SOURCE[0]}")"
set -x

pwd | cat > /tmp/dist
dist=$(cat /tmp/dist)
xfce4-terminal --geometry=62x24 --hide-scrollbar --hide-toolbar --hide-borders --working-directory=$dist -e "./notornameON"

if [ -f vpn2.conf ]; 
	then 
		sudo ./namespaced-openvpn --config vpn2.ovpn --auth-user-pass vpn2.conf
	else
		sudo ./namespaced-openvpn --config vpn2.ovpn
fi
