#!/bin/bash
cd "$( dirname "${BASH_SOURCE[0]}")"
set -x

wifi_iface=$(sed '4!d' variables.conf)
pwd | cat > /tmp/dist
dist=$(cat /tmp/dist)

cat /sys/class/net/$wifi_iface/phy80211/name > /tmp/wifi_phy
sudo cp /etc/NetworkManager/NetworkManager.conf /etc/NetworkManager/NetworkManager.old
sudo sed -i 15c\unmanaged-devices=interface-name:$wifi_iface NetworkManager.conf
sudo cp NetworkManager.conf /etc/NetworkManager/NetworkManager.conf
nm_pid=$(sudo pidof NetworkManager)
sudo kill -HUP $nm_pid
xfce4-terminal --geometry=62x24 --hide-scrollbar --hide-toolbar --working-directory=$dist -e "./nvpnon"

if [ -f vpn1.conf ]; 
	then 
		sudo openvpn --config vpn1.ovpn --auth-user-pass vpn1.conf
	else
		sudo openvpn --config vpn1.ovpn
fi
